"native-plants": [{
    "id": "",
    "image_url": [""],
    "common_name": "Wood Fern",
    "scientific_name": "Dryopteris arguta",
    "isNative": true,
    "invasive_rank": "",
    "is_erradication_req": false,
    "plant_community": ["western hemlock-douglas fir forest",
                        "mixed coniferous/deciduous riparian forest",
                        "wet rocky outcrops"],
    "plant_type": "fern",
    "mature_height": "18–24 in.",
    "habitat_type": ["herbacious", "grasses"],
    "life_cycle": "Evergreen perennial",
    "light": ["full sun", "part sun"],
    "moisture": ["dry", "moist"],
    "description": null,
    "has_flowers": false,
    "flowers": {
        "showy": false,
        "colors": ["yellow"],
        "notes": null,
        "flowering_months": [],
        }
    },

    {
    "id": "",
    "image_url": [""],
    "common_name": "Canary Violet",
    "scientific_name": "Viola praemorsa var. praemorsa",
    "isNative": true,
    "invasive_rank": "",
    "is_erradication_req": false,
    "plant_community": ["prarie", "grasses"],
    "plant_type": "forb",
    "mature_height": null,
    "habitat_type": ["grassland"],
    "life_cycle": null,
    "light": ["part sun"],
    "moisture": ["dry"],
    "description": null,
    "has_flowers": false,
    "flowers": {
        "showy": false,
        "colors": [],
        "notes": null,
        "flowering_months": [null],
        }
    },

    {
    "id": "",
    "image_url": [""],
    "common_name": "White-Tip Clover",
    "scientific_name": "Trifolium variegatum",
    "isNative": true,
    "invasive_rank": "",
    "is_erradication_req": false,
    "plant_community": ["prarie"],
    "plant_type": "forb",
    "mature_height": null,
    "habitat_type": ["grassland"],
    "life_cycle": null,
    "light": ["full sun"],
    "moisture": ["dry"],
    "description": null,
    "has_flowers": false,
    "flowers": {
        "showy": false,
        "colors": [],
        "notes": null,
        "flowering_months": [null],
        }
    },
    {
        "id": "",
        "image_url": [""],
        "common_name": "Sand Clover",
        "scientific_name": "Trifolium willdenovii",
        "isNative": true,
        "invasive_rank": "",
        "is_erradication_req": false,
        "plant_community": ["prarie"],
        "plant_type": "forb",
        "mature_height": null,
        "habitat_type": ["grassland"],
        "life_cycle": null,
        "light": ["part sun"],
        "moisture": ["dry"],
        "description": null,
        "has_flowers": false,
        "flowers": {
            "showy": false,
            "colors": [],
            "notes": null,
            "flowering_months": [null],
            },

    {
        "id": "",
        "image_url": [""],
        "common_name": "American Bulrush",
        "scientific_name": "Schoenoplectus pungens",
        "isNative": true,
        "invasive_rank": "",
        "is_erradication_req": false,
        "plant_community": ["marsh"],
        "plant_type": "Sedge/Rush",
        "mature_height": ["6-40 in."],
        "habitat_type": ["wetland"],
        "life_cycle": ["Evergreen perennial"],
        "light": ["part sun"],
        "moisture": ["Pernl wet", "sub"],
        "description": null,
        "has_flowers": false,
        "flowers": {
            "showy": false,
            "colors": [],
            "notes": null,
            "flowering_months": [null],
            },

    {
        "id": "",
        "image_url": [""],
        "common_name": "Common Cattail",
        "scientific_name": "Typha latifolia",
        "isNative": true,
        "invasive_rank": "",
        "is_erradication_req": false,
        "plant_community": ["scrub-shrub wetlands", 
                            "marsh"],
        "plant_type": "Other",
        "mature_height": ["4-10 in."],
        "habitat_type": ["wetland"],
        "life_cycle": ["Evergreen perennial"],
        "light": ["full sun", "part sun"],
        "moisture": ["Pernl wet", "sub"],
        "description": null,
        "has_flowers": false,
        "flowers": {
            "showy": true,
            "colors": ["brown"],
            "notes": "Brown; tiny in terminal cylindrical spike up to 12 inches long",
            "flowering_months": [null],
            },
    ]

